### ISSUE TITLE
Addon issues - fails when loading the channel list

### ISSUE THREAD

**Issue by remus77** [beardypig/plugin.video.blxdtvcatchup#2]
I think they may have changed the API.
I've had a go at the code but I'm a novice with python and can't fathom how the links are supposed to be laid out.  It's definitely failing when it accesses the appcache but that could be because it's not reading everything it's supposed to.
I have tried to replicate the links manually but can't quite get it to work.
If someone could help me along I would be very happy to help in developing the app

13:00:31 T:1423246208 WARNING: TVA Log Uploader: Uploader Error: (TvaddonsUploader) kodi.log: <urlopen error [Errno 4] non-recoverable failure in name resolution.>
13:01:14 T:1423246208 WARNING: TVA Log Uploader: Uploader Error: <urlopen error [Errno 4] non-recoverable failure in name resolution.>
13:01:14 T:1423246208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 4] non-recoverable failure in name resolution.>
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvaddons.debug.log/default.py", line 127, in <module>
                                                sys.exit(main())
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvaddons.debug.log/default.py", line 120, in main
                                                upload_logs()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvaddons.debug.log/default.py", line 77, in upload_logs
                                                result = log_service.upload_log(log, name)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvaddons.debug.log/lib/uploaders/dropbox.py", line 39, in upload_log
                                                token = self.__authorize()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvaddons.debug.log/lib/uploaders/dropbox.py", line 68, in __authorize
                                                return token
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvaddons.debug.log/lib/db_auth.py", line 40, in __exit__
                                                self.remove_session()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvaddons.debug.log/lib/db_auth.py", line 50, in remove_session
                                                return self.__http_request(data=data)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.tvaddons.debug.log/lib/db_auth.py", line 74, in __http_request
                                                response = urllib2.urlopen(request)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 391, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 409, in _open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 1169, in https_open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 1136, in do_open
                                            URLError: <urlopen error [Errno 4] non-recoverable failure in name resolution.>
                                            -->End of Python script error report<--

**Comment by remus77** [comment]
Never mind - Has resolved itself.  Must have been an issue with the API on the site

**Comment by remus77** [comment]
Now happening again...

**Comment by beardypig** [comment]
I am in the process of releasing `2.0.1` which should resolve this issue :)

**Comment by beardypig** [comment]
This was resolved in `2.0.1`, but is broken again. Should be fixed in `2.1.0`.
